### ISSUE TITLE
KeyError during python manage.py generateschema in drf 3.12.2

### ISSUE THREAD

**Issue by spankratov** [best-doctor/restdoctor#13]
Command to reproduce:
`python manage.py generateschema --urlconf api.v1.urls --generator_class restdoctor.rest_framework.schema.RefsSchemaGenerator`

Traceback:
```
Traceback (most recent call last):
  File "/buktop/manage.py", line 17, in <module>
    main()
  File "/buktop/manage.py", line 13, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/management/commands/generateschema.py", line 41, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/usr/local/lib/python3.9/site-packages/restdoctor/rest_framework/schema.py", line 165, in get_schema
    paths = self.get_paths(None if public else request)
  File "/usr/local/lib/python3.9/site-packages/restdoctor/rest_framework/schema.py", line 115, in get_paths
    operation = view.schema.get_operation(path, method)
  File "/usr/local/lib/python3.9/site-packages/restdoctor/rest_framework/schema.py", line 194, in get_operation
    operation = super().get_operation(path, method)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/schemas/openapi.py", line 159, in get_operation
    operation['responses'] = self.get_responses(path, method)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/schemas/openapi.py", line 665, in get_responses
    response_schema = paginator.get_paginated_response_schema(response_schema)
  File "/usr/local/lib/python3.9/site-packages/restdoctor/rest_framework/pagination.py", line 129, in get_paginated_response_schema
    meta = schema['properties'].get('meta', {'type': 'object', 'properties': {}})
KeyError: 'properties'
```

Error is present with drf 3.12.2 but everything is fine with drf 3.11.2

**Comment by sergey-jerzy** [comment]
Fixed in 0.0.11
